language: node_js
services:
  - mongodb
before_script:
  - sleep 15
  - mongo techtalks --eval 'db.addUser("travis", "test");'
env:
  - DBURL="mongodb://travis:test@localhost:27017/techtalks"
node_js:
  - 0.12
install:
  - npm install
notifications:
  slack: tlksio:fNbJkMIvB9GZKDDjfjZqAzBb
